### ISSUE TITLE
`multichain-tools' has no exported member named 'ChainSignaturesContract'

### ISSUE THREAD

**Issue by urataps** [Pessina/near-sandbox#4]
HI I just cloned the repo tried to run it locally but I get the ChainSignaturesContract is undefined error.
<img width="772" alt="image" src="https://github.com/user-attachments/assets/164e29e8-f661-4992-977f-3c74e01023be">

It seems it's imported from multichain-tools package, but my guess is that it's not available in the newest version. Any clues how to fix this? Is there a new api in the newest version that wasn't introduced?

**Comment by urataps** [comment]
@Pessina

**Comment by Pessina** [comment]
Hey @urataps , 

Can you please pull the latest `main` and try again? I just pushed a fix for this. 

I'm sorry, I was developing and didn't noticed the main was broken. 

Also please note you need to set the .env and the txHash will be logged on the console. I need to make some UX improvements. 

Please let me know if you manage to get it working.

**Comment by urataps** [comment]
Hey @Pessina thanks for getting so fast to me. I'm currently participating in the REDACTED hackathon so time is of the essence.

While I'm able to run the frontend now, the transactions are not being relayed to the destination chain for some reason.

**Comment by Pessina** [comment]
@urataps, that's weird, I'm able to send a tx in ETH, BNB and Cosmos (BTC i didn't tested, I don't have funds).

I'm going to the office now and will have a look at it. 

Please ping me on telegram so we can iterate faster on it my id is @sansoroi
